### ISSUE TITLE
Leaderboard not in the right order

### ISSUE THREAD

**Issue by Folas1337** [TomDesch/MC2048#1]
I've just had a few rounds of 2048 and someone else beat me but they show up as number 2 even though they clearly beat me:
![image](https://github.com/TomDesch/MC2048/assets/39222968/47e609e9-5ef8-428a-9d54-745304dd1992)

I mean it still says on the bottom that "Your Position: 2" but shouldn't LenaTheEevee show up above me and be labelled 1 and not 2?

Just a small thing, otherwise the plugin appears to be working great and is lots of fun 😄

**Comment by TomDesch** [comment]
I'm sorry I never noticed this issue until I got your closing email.
I'll look into it!

**Comment by Folas1337** [comment]
Haha, I'm not using the plugin anymore and thus can't even give any feedback if you ever fix it or do anything about it which is why I closed it.

What I'm saying is you're on your own when you'll be fixing it 😅

**Comment by TomDesch** [comment]
Fixed in most recent version
