### ISSUE TITLE
Suggestion - Custom Model Data Support.

### ISSUE THREAD

**Issue by WMGameLive** [TomDesch/MC2048#2]
Make all numbers and buttons support custom model data, so that servers with resourcepack can make the gui more refined.

**Comment by TomDesch** [comment]
Hey
I'm not sure what you mean by that
The config already supports fully customizable item usages and names for all "number" items.
I'll see to add that for the buttons too.

Edit: Please add me on discord if you wish for better communication (StealingDaPenta)

**Comment by TomDesch** [comment]
Added 
    MATERIAL_GUI_FILLER("WHITE_STAINED_GLASS_PANE"),
    MATERIAL_BUTTON_UP("LIGHTNING_ROD"),
    MATERIAL_BUTTON_RIGHT("LIGHTNING_ROD"),
    MATERIAL_BUTTON_LEFT("LIGHTNING_ROD"),
    MATERIAL_BUTTON_DOWN("LIGHTNING_ROD"),
    MATERIAL_BUTTON_UNDO("AXOLOTL_BUCKET"),
    MATERIAL_BUTTON_UNDO_USED("BUCKET"),
    MATERIAL_GUI_PLAYER("PLAYER_HEAD"),

**Comment by WMGameLive** [comment]
> Hey I'm not sure what you mean by that The config already supports fully customizable item usages and names for all "number" items. I'll see to add that for the buttons too.
> 
> Edit: Please add me on discord if you wish for better communication (StealingDaPenta)

What? You don't know CustomModelData? That's a thing that has existed for a very very long time.
CustomModelData allows modifying an item's model and texture through a resource pack. Items with CustomModelData can be given using commands or plugins.

By vanilla command: `/give WMGameLive minecraft:dirt[minecraft:custom_model_data=10000]`
By plugin code: `ItemMeta.setCustomModelData(int)`

**Comment by TomDesch** [comment]
done.
